# Generated by Django 4.2.20 on 2026-04-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_useraccount_faltas_agresivas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('estrategico', 'Estratégico'), ('tactico', 'Táctico'), ('operaciones', 'Operaciones')], default='estudiante', max_length=20, verbose_name='Rol de Usuario'),
        ),
    ]
