# Generated by Django 4.2.20 on 2026-04-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_useraccount_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('estrategico', 'Estratégico'), ('tactico', 'Táctico'), ('operaciones', 'Operaciones')], default='operativo', max_length=20, verbose_name='Rol de Usuario'),
        ),
    ]
